steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-t",
              "us-central1-docker.pkg.dev/gcp-class-16/chloe-alexander-hao-banking-repo/bank-backend",
              "./cloud-run/bank-backend",
          ]

    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "push",
              "us-central1-docker.pkg.dev/gcp-class-16/chloe-alexander-hao-banking-repo/bank-backend",
          ]

    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: gcloud
      args:
          [
              "run",
              "deploy",
              "bank-backend",
              "--image",
              "us-central1-docker.pkg.dev/gcp-class-16/chloe-alexander-hao-banking-repo/bank-backend",
              "--region",
              "us-central1",
              "--platform",
              "managed",
              "--allow-unauthenticated",
          ]

images:
    - "us-central1-docker.pkg.dev/gcp-class-16/chloe-alexander-hao-banking-repo/bank-backend"

options:
    logging: CLOUD_LOGGING_ONLY
