steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/gcp-class-16/chloe-alexander-hao-banking-repo/bank-frontend',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/gcp-class-16/chloe-alexander-hao-banking-repo/bank-frontend'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'bank-frontend',
        '--image',
        'us-central1-docker.pkg.dev/gcp-class-16/chloe-alexander-hao-banking-repo/bank-frontend',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'us-central1-docker.pkg.dev/gcp-class-16/chloe-alexander-hao-banking-repo/bank-frontend'